### ISSUE TITLE
Where to add google api key

### ISSUE THREAD

**Issue by PradeepN93** [ibrarturi/yii2-latlon-finder#1]
Hi ibrarturi, I install your plugin and added the code that i got in github but there is an error ,Google Maps API error: MissingKeyMapError,Pls suggest where to add the api key in Yii2.

**Comment by ibrarturi** [comment]
Hi PradeepN93, 
Thanks for using my plugin :-)
To solve the above mentioned issue, please follow the following steps:

- Goto this url: https://developers.google.com/maps/documentation/javascript/get-api-key to get your google map api key
- Replace the following line

 `$view->registerJsFile('https://maps.googleapis.com/maps/api/js', ['position' => View::POS_HEAD]);`

 with the below line

 `$view->registerJsFile('https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY', ['position' => View::POS_HEAD]);`  

in LatLngFinder.php file on line # 183
- This should do the trick
